/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class affiliationexposureJNI {
  public final static native void ModeInfo_first_mode_indices_set(long jarg1, ModeInfo jarg1_, int jarg2);
  public final static native int ModeInfo_first_mode_indices_get(long jarg1, ModeInfo jarg1_);
  public final static native void ModeInfo_second_mode_indices_set(long jarg1, ModeInfo jarg1_, int jarg2);
  public final static native int ModeInfo_second_mode_indices_get(long jarg1, ModeInfo jarg1_);
  public final static native void ModeInfo_first_mode_flag_set(long jarg1, ModeInfo jarg1_, String jarg2);
  public final static native String ModeInfo_first_mode_flag_get(long jarg1, ModeInfo jarg1_);
  public final static native long new_ModeInfo();
  public final static native void delete_ModeInfo(long jarg1);
  public final static native void read_y_mode_file(String jarg1, long jarg2, long jarg3, long jarg4, boolean jarg5, String jarg6);
  public final static native void init_a_matrix(long jarg1, long jarg2, ModeInfo jarg2_);
  public final static native void setup_mode_data(String jarg1, boolean jarg2, long jarg3, ModeInfo jarg3_);
  public final static native long generateAMatrix(String jarg1, long jarg2, long jarg3, boolean jarg4, long jarg5, ModeInfo jarg5_);
  public final static native long generateAPrimeMatrix(long jarg1, long jarg2, ModeInfo jarg2_);
  public final static native long transposeAMatrix(long jarg1, long jarg2, long jarg3, ModeInfo jarg3_);
  public final static native void calc_affiliation_exposure(long jarg1, long jarg2, long jarg3, long jarg4, ModeInfo jarg4_);
  public final static native void print_aff_exposure_values(long jarg1, long jarg2, long jarg3, ModeInfo jarg3_);
}
