/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class affiliationexposure {
  public static void read_y_mode_file(String path, SWIGTYPE_p_p_double yArray, SWIGTYPE_p_int first_mode_array, SWIGTYPE_p_int second_mode_array, boolean HAS_HEADER, String first_mode_flag) {
    affiliationexposureJNI.read_y_mode_file(path, SWIGTYPE_p_p_double.getCPtr(yArray), SWIGTYPE_p_int.getCPtr(first_mode_array), SWIGTYPE_p_int.getCPtr(second_mode_array), HAS_HEADER, first_mode_flag);
  }

  public static void init_a_matrix(SWIGTYPE_p_p_double wMatrix, ModeInfo mode_data) {
    affiliationexposureJNI.init_a_matrix(SWIGTYPE_p_p_double.getCPtr(wMatrix), ModeInfo.getCPtr(mode_data), mode_data);
  }

  public static void setup_mode_data(String yPathFile, boolean HAS_HEADER, ModeInfo mode_data) {
    affiliationexposureJNI.setup_mode_data(yPathFile, HAS_HEADER, ModeInfo.getCPtr(mode_data), mode_data);
  }

  public static SWIGTYPE_p_p_double generateAMatrix(String netPathFile, SWIGTYPE_p_int f_mode_array, SWIGTYPE_p_int s_mode_array, boolean HAS_HEADER, ModeInfo mode_data) {
    long cPtr = affiliationexposureJNI.generateAMatrix(netPathFile, SWIGTYPE_p_int.getCPtr(f_mode_array), SWIGTYPE_p_int.getCPtr(s_mode_array), HAS_HEADER, ModeInfo.getCPtr(mode_data), mode_data);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_p_double generateAPrimeMatrix(SWIGTYPE_p_p_double aMatrix, ModeInfo mode_data) {
    long cPtr = affiliationexposureJNI.generateAPrimeMatrix(SWIGTYPE_p_p_double.getCPtr(aMatrix), ModeInfo.getCPtr(mode_data), mode_data);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_p_double transposeAMatrix(SWIGTYPE_p_p_double aMatrix, SWIGTYPE_p_p_double aPrimeMatrix, ModeInfo mode_data) {
    long cPtr = affiliationexposureJNI.transposeAMatrix(SWIGTYPE_p_p_double.getCPtr(aMatrix), SWIGTYPE_p_p_double.getCPtr(aPrimeMatrix), ModeInfo.getCPtr(mode_data), mode_data);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public static void calc_affiliation_exposure(SWIGTYPE_p_p_double cMatrix, SWIGTYPE_p_p_double eArray, SWIGTYPE_p_p_double yArray, ModeInfo mode_data) {
    affiliationexposureJNI.calc_affiliation_exposure(SWIGTYPE_p_p_double.getCPtr(cMatrix), SWIGTYPE_p_p_double.getCPtr(eArray), SWIGTYPE_p_p_double.getCPtr(yArray), ModeInfo.getCPtr(mode_data), mode_data);
  }

  public static void print_aff_exposure_values(SWIGTYPE_p_p_double y_array, SWIGTYPE_p_p_double e_array, ModeInfo mode_data) {
    affiliationexposureJNI.print_aff_exposure_values(SWIGTYPE_p_p_double.getCPtr(y_array), SWIGTYPE_p_p_double.getCPtr(e_array), ModeInfo.getCPtr(mode_data), mode_data);
  }

  public static SWIGTYPE_p_int new_intp() {
    long cPtr = affiliationexposureJNI.new_intp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_int copy_intp(int value) {
    long cPtr = affiliationexposureJNI.copy_intp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intp(SWIGTYPE_p_int obj) {
    affiliationexposureJNI.delete_intp(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void intp_assign(SWIGTYPE_p_int obj, int value) {
    affiliationexposureJNI.intp_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int intp_value(SWIGTYPE_p_int obj) {
    return affiliationexposureJNI.intp_value(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static SWIGTYPE_p_p_double double_array(int rows, int cols) {
    long cPtr = affiliationexposureJNI.double_array(rows, cols);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_void setitem(SWIGTYPE_p_p_double array, int row, int col, int value) {
    long cPtr = affiliationexposureJNI.setitem(SWIGTYPE_p_p_double.getCPtr(array), row, col, value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public static SWIGTYPE_p_int int_array(int size) {
    long cPtr = affiliationexposureJNI.int_array(size);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

}
