/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class ModeInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ModeInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModeInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        affiliationexposureJNI.delete_ModeInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setFirst_mode_indices(int value) {
    affiliationexposureJNI.ModeInfo_first_mode_indices_set(swigCPtr, this, value);
  }

  public int getFirst_mode_indices() {
    return affiliationexposureJNI.ModeInfo_first_mode_indices_get(swigCPtr, this);
  }

  public void setSecond_mode_indices(int value) {
    affiliationexposureJNI.ModeInfo_second_mode_indices_set(swigCPtr, this, value);
  }

  public int getSecond_mode_indices() {
    return affiliationexposureJNI.ModeInfo_second_mode_indices_get(swigCPtr, this);
  }

  public void setFirst_mode_flag(String value) {
    affiliationexposureJNI.ModeInfo_first_mode_flag_set(swigCPtr, this, value);
  }

  public String getFirst_mode_flag() {
    return affiliationexposureJNI.ModeInfo_first_mode_flag_get(swigCPtr, this);
  }

  public ModeInfo() {
    this(affiliationexposureJNI.new_ModeInfo(), true);
  }

}
