/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class networkexposureJNI {
  public final static native void calc_network_exposure(long jarg1, long jarg2, long jarg3, int jarg4);
  public final static native void read_net_file(String jarg1, long jarg2, boolean jarg3);
  public final static native int getDimension(String jarg1, boolean jarg2);
  public final static native void read_y_file(String jarg1, long jarg2, boolean jarg3);
  public final static native void init_w_matrix(long jarg1, long jarg2);
  public final static native void print_net_exposure_values(long jarg1, long jarg2, int jarg3);
  public final static native long new_intp();
  public final static native long copy_intp(int jarg1);
  public final static native void delete_intp(long jarg1);
  public final static native void intp_assign(long jarg1, int jarg2);
  public final static native int intp_value(long jarg1);
  public final static native long double_array(int jarg1, int jarg2);
  public final static native long setitem(long jarg1, int jarg2, int jarg3, int jarg4);
}
