/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class networkexposure {
  public static void calc_network_exposure(SWIGTYPE_p_p_double wMatrix, SWIGTYPE_p_p_double yArray, SWIGTYPE_p_p_double eArray, int matrix_dim) {
    networkexposureJNI.calc_network_exposure(SWIGTYPE_p_p_double.getCPtr(wMatrix), SWIGTYPE_p_p_double.getCPtr(yArray), SWIGTYPE_p_p_double.getCPtr(eArray), matrix_dim);
  }

  public static void read_net_file(String path, SWIGTYPE_p_p_double wMatrix, boolean HAS_HEADER) {
    networkexposureJNI.read_net_file(path, SWIGTYPE_p_p_double.getCPtr(wMatrix), HAS_HEADER);
  }

  public static int getDimension(String pathYFile, boolean HAS_HEADER) {
    return networkexposureJNI.getDimension(pathYFile, HAS_HEADER);
  }

  public static void read_y_file(String path, SWIGTYPE_p_p_double yArray, boolean HAS_HEADER) {
    networkexposureJNI.read_y_file(path, SWIGTYPE_p_p_double.getCPtr(yArray), HAS_HEADER);
  }

  public static void init_w_matrix(SWIGTYPE_p_p_double wMatrix, SWIGTYPE_p_int matrix_dim) {
    networkexposureJNI.init_w_matrix(SWIGTYPE_p_p_double.getCPtr(wMatrix), SWIGTYPE_p_int.getCPtr(matrix_dim));
  }

  public static void print_net_exposure_values(SWIGTYPE_p_p_double y_array, SWIGTYPE_p_p_double e_array, int matrix_dim) {
    networkexposureJNI.print_net_exposure_values(SWIGTYPE_p_p_double.getCPtr(y_array), SWIGTYPE_p_p_double.getCPtr(e_array), matrix_dim);
  }

  public static SWIGTYPE_p_int new_intp() {
    long cPtr = networkexposureJNI.new_intp();
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static SWIGTYPE_p_int copy_intp(int value) {
    long cPtr = networkexposureJNI.copy_intp(value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public static void delete_intp(SWIGTYPE_p_int obj) {
    networkexposureJNI.delete_intp(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static void intp_assign(SWIGTYPE_p_int obj, int value) {
    networkexposureJNI.intp_assign(SWIGTYPE_p_int.getCPtr(obj), value);
  }

  public static int intp_value(SWIGTYPE_p_int obj) {
    return networkexposureJNI.intp_value(SWIGTYPE_p_int.getCPtr(obj));
  }

  public static SWIGTYPE_p_p_double double_array(int rows, int cols) {
    long cPtr = networkexposureJNI.double_array(rows, cols);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_double(cPtr, false);
  }

  public static SWIGTYPE_p_void setitem(SWIGTYPE_p_p_double array, int row, int col, int value) {
    long cPtr = networkexposureJNI.setitem(SWIGTYPE_p_p_double.getCPtr(array), row, col, value);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

}
